### PR TITLE
Allow specifying of rules manually

### PR DESCRIPTION
**Pull request by morrislaptop**
When manually specifying keys because of migrating existing db / json fields, the ConditionalLogic class can't / won't use the manually specified key.

This change allows the rules to be specified manually and bypass the ConditionalLogic class.

Example:

```php
TrueFalse::make('Display Webinar Chapters?')
  ->key('field_64c842b5238bc'),

Text::make('Webinar Chapters')
  ->key('field_64c8422d238b7')
  ->conditionalLogic([
      ['field' => 'field_64c842b5238bc', 'operator' => '==', 'value' => 1]
  ])
```

### CODE REVIEW

**Comment by vinkla** [comment]
Thank you for the pull request! I appreciate the use case. I've started migrating a project from JSON to PHP too. Please include tests for this change and let's add a code comment to explain the reason for the implementation. Additionally, we should convert this into a regular function.

**Comment by morrislaptop** [comment]
@vinkla added test and comment. Not sure what / why we need to convert into a regular function?

**Comment by vinkla** [comment]
> Not sure what / why we need to convert into a regular function?

Just to make the code more readable. I can make that adjustment.

**Comment by vinkla** [comment]
I have come up with another solution.

```php
ConditionalLogic::where(
    name: 'select',
    operator: '==',
    value: 'red',
    key: 'field_123abc'
)
```

Please use the branch alias "13.9" to test this feature. We will release it after a period of testing.

Thanks for the pull request Craig 🙌

**Comment by morrislaptop** [comment]
Great!

**Pull request merged**
