### PR TITLE
Adding PostStatus filter

### LINKED ISSUE #137: Relationship field : PostStatus filter is missing
Hi,

First of all, thanks for this awesome wrapper !
I've searched for the Relationship field and it seems to use Trait for filtering by PostType and by Taxonomies.
But in the ACF documentation for this field ( https://www.advancedcustomfields.com/resources/relationship/#settings Filter by Post Status ) It's also possible to filter by post status.
I don't find anything related to this feature in the Relationship class

Am I missing something ?

Thanks

### PR DESCRIPTION
**Pull request by gturpin-dev**
Fix #137 
Add the PostStatus filter to the FilterBy trait because filtering by post_status is possible for multiple fields and not only the Relationship

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request, please also add a test case.

**Comment by gturpin-dev** [comment]
@vinkla Done, I've tried to follow your type of tests. So I added a test case on Relationship field

**Comment by vinkla** [comment]
Thanks @gturpin-dev 🙌  

This wont be released just yet, you may use the branch alias in the mean time.

```json
{
    "require": {
        "vinkla/extended-acf": "^13.8"
     },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by gturpin-dev** [comment]
Thanks to you.
Also thanks to add improved code on top of mine.
It could be an improvement to allows each post status currently registered instead of the WP default hardcoded.
But it's maybe not the goal of the package to check things as far as that.
Or it could be possible to add a hook to extend this list if needed 🤷‍♂️ 

Anyways, thanks ! 👌

**Comment by vinkla** [comment]
> It could be an improvement to allows each post status currently registered instead of the WP default hardcoded.

What other post statuses do people use? Is it common to use non-default statuses?

**Comment by gturpin-dev** [comment]
I don't think so, it's rare, which is why I just listed it as an optional enhancement.
There are plugins that allow you to create custom statuses, but this WP feature is hard to extend.

**Comment by vinkla** [comment]
Great! Let's maintain the current implementation and reassess the situation in the future if there's a request for it.

**Pull request merged**
