### PR TITLE
Version 14

### PR DESCRIPTION
**Pull request by vinkla**
This version introduces new method and trait names to improve the developer experience. Please refer to the upgrade guide for a [complete list of changes](https://github.com/vinkla/extended-acf/tree/develop?tab=readme-ov-file#14). 

We welcome any suggestions for improvements in the next major version!

### CODE REVIEW

**Comment by vinkla** [comment]
Pinging project users for early feedback:

- @Grafikart
- @fiskhandlarn
- @gojsse
- @ChrisGaney
- @lindseyolson
- @Kimla
- @kaelansmith
- @ogorzalka
- anyone else using this package
- etc. 

I have reviewed the project with a fresh perspective to improve the developer experience. Instead of using the ACF naming convention, I have tried to create more readable names that don't require you to refer to the documentation. If any of you have a minute to spare, please share your thoughts on this update.

Please review the [upgrade guide](https://github.com/vinkla/extended-acf/tree/develop?tab=readme-ov-file#14) for the next version and the ideas mentioned in the description above.

**Comment by ogorzalka** [comment]
Hi ! 

Great :) Laravel spirit inside !

**Comment by kaelansmith** [comment]
looks good, no concerns/feedback from me :)

**Comment by vinkla** [comment]
We plan to release the new version next week. Please test it as soon as possible!

```diff
"require": {
-    "vinkla/extended-acf": "^13.0",
+    "vinkla/extended-acf": "^14.0",
},
-"minimum-stability": "stable",
+"minimum-stability": "dev",
```

**Pull request merged**
